# fly.toml app configuration file generated for nice-chat-app on 2023-08-02T00:55:08+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nice-chat-app"
primary_region = "sin"

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
